version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Japan
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sentry-rails
    versions:
    - 4.1.6
    - 4.1.7
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.3.0
    - 4.3.1
    - 4.3.2
    - 4.3.3
  - dependency-name: i18n-js
    versions:
    - 3.8.0
    - 3.8.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: pygments.rb
    versions:
    - 2.0.0
    - 2.1.0
  - dependency-name: sendgrid-ruby
    versions:
    - 6.3.8
    - 6.3.9
  - dependency-name: sentry-ruby
    versions:
    - 4.1.5
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
