FROM solr:7
RUN precreate-core development
RUN precreate-core test
COPY solr/solrconfig.xml /opt/solr/server/solr/mycores/development/conf/solrconfig.xml
COPY solr/schema.xml /opt/solr/server/solr/mycores/development/conf/schema.xml
COPY solr/solrconfig.xml /opt/solr/server/solr/mycores/test/conf/solrconfig.xml
COPY solr/schema.xml /opt/solr/server/solr/mycores/test/conf/schema.xml

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-foreground"]
