test:
  adapter: mysql2
  database: revenger_test
  host: 127.0.0.1
  reconnect: true
  username: root

development:
  adapter: mysql2
  database: revenger_development
  host: 127.0.0.1
  reconnect: true
  username: root
