production:
  solr:
    hostname: localhost
    port: 8080
    log_level: WARNING
    path: '/solr/production'
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8983
    path: '/solr/development'
    log_level: INFO

test:
  solr:
    hostname: <%= ENV['CI'] ? 'localhost': 'solr' %>
    port: 8983
    path: '/solr/test'
    log_level: INFO
