production:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: '/solr/mycore'
    # read_timeout: 2
    # open_timeout: 0.5

staging:
  solr:
    hostname: solr
    port: 8983
    log_level: WARNING
    path: '/solr/mycore'
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: solr
    port: 8983
    path: '/solr/mycore'
    log_level: INFO

test:
  solr:
    hostname: solr
    port: 8983
    path: '/solr/mycore'
    log_level: WARNING
